### ISSUE TITLE
does the lwrp honor notifies?

### ISSUE THREAD

**Issue by corbesero** [jrwesolo/limits#11]
I tried the following lwrp

```
limits_config 'system-wide limits' do
  limits [
    { domain: '*', type: 'hard', item: 'nofile', value: 32_768 },
    { domain: '*', type: 'soft', item: 'nofile', value: 32_768 }
  ]
  use_system true
  notifies :restart, 'service[sshd]'
end
```

but...

my chef-client would bail almost immediately .  no error.  but none of my resources would run.
when i took the line out, everything was fine.

**Comment by jrwesolo** [comment]
I'll have to take a look! Thanks for calling this out.
