### ISSUE TITLE
Can't set system or user specific noproc settings for Centos 6.5?

### ISSUE THREAD

**Issue by JoeReid-Korrelate** [jrwesolo/limits#6]
I can't set the noproc settings on CentOS 6.5.   I need to increase the system wide limits (or at least the user specific limits) for HBase.

I've tried setting the limits both as a starred out user and as hbase specifically.  
```
# Set soft and hard limits system-wide for the number of processes a user can run.
set_limit 'hbase' do
  type 'soft'
  item 'noproc'
  value 65536
  use_system true
end

set_limit '*' do
  type 'hard'
  item 'noproc'
  value 65536
  use_system true
end
```

The code doesn't throw an error or even a warning out to the terminal.  It only adds the following commented line to the `/etc/security/limits.conf file`:

```
# The following limits were detected as invalid by Chef
# hbase soft noproc 65536
# hbase hard noproc 65536

# The following limits were detected as invalid by Chef
# * soft noproc 65536
# * hard noproc 65536`
```

**Versions:**
```
chef (12.2.1)
chef-dk (0.5.0.rc.5)
chef-vault (2.4.0)
chef-zero (4.2.1, 1.5.6)
```

I initially thought it was related to [/etc/security/limits.d/90-nproc.conf](http://serverfault.com/questions/544171/etc-security-limits-conf-soft-nproc-limit-appears-to-be-ignored) and wrote code to remove that file.  But this appears to be a Chef thing.

How can I resolve this?

**Comment by jrwesolo** [comment]
Hello @JoeReid-Korrelate, try using `nproc` instead of `noproc`. I don't believe `noproc` is a valid item. You can see http://linux.die.net/man/5/limits.conf for a full list of valid settings.

**Comment by JoeReid-Korrelate** [comment]
Hey @jrwesolo , 

Wow.  Duh.  Okay, great.   I love an easy fix!  

Thanks for your input, and the quick response.

Regards,
Joe Reid

PS - Posting output, for posterity:

```
10.0.1.56       --- /etc/security/limits.conf	2015-04-24 20:33:56.677119211 +0000
10.0.1.56       +++ /tmp/chef-rendered-template20150424-21492-yk71kc	2015-04-24 20:56:10.030136866 +0000
10.0.1.56       @@ -3,10 +3,8 @@
10.0.1.56
10.0.1.56        * soft nofile 65536
10.0.1.56        * hard nofile 65536
10.0.1.56       -
10.0.1.56       -# The following limits were detected as invalid by Chef
10.0.1.56       -# hbase soft noproc 65536
10.0.1.56       -# hbase hard noproc 65536
10.0.1.56       +* soft nproc  65536
10.0.1.56       +* hard nproc  65536
```

**Comment by jrwesolo** [comment]
You're welcome! Glad you got it working.
