### ISSUE TITLE
Is there a way to generate limit files under the limits.d directory?

### ISSUE THREAD

**Issue by Joseph-R** [jrwesolo/limits#7]
I've been using this cookbook for awhile now and all of my configs end up in limits.conf.  Is there a way to spread these out under the limits.d directory?

**Comment by jrwesolo** [comment]
Hello @Joseph-R! Absolutely. That is the intended design of this cookbook. If you take a look at the README.md you should see what your looking for. Are you using the `set_limit` definition or the `limits_config` LWRP in your code? Both have an attribute called `use_system`. That defaults to `false` so it should be creating the configs under the limits.d directory automatically. It should only be setting the limits.conf file if your are passing `use_system true`.

**Comment by Joseph-R** [comment]
Ah, okay.  I guess I didn't fully understand that from the README.md.  

All of my code atm looks like this:
```
set_limit '*' do
  type 'hard'
  item 'nofile'
  value 65536
  use_system true
end

# Set soft and hard limits system-wide for the number of processes a user can run.
set_limit '*' do
  type 'soft'
  item 'nproc'
  value 487503
  use_system true
end
```

I'll drop the `use_system` flag and run it through test kitchen.  Thanks!

Regards,
Joe Reid
