### ISSUE TITLE
Documentation request - what ulimits can cookbook set?

### ISSUE THREAD

**Issue by spuder** [jrwesolo/limits#9]
Here are all the available options that can be set with ulimit. 

```bash
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4864
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

Looking through the source, I find the list of available items here:

https://github.com/jrwesolo/limits/blob/1a2a3ee4a2b5069dafeca8c1d3f87ebfa34d43a2/libraries/default.rb#L8-L10  

    core data fsize memlock nofile rss stack cpu nproc as maxlogins maxsyslogins priority locks sigpending  msgqueue nice rtprio

I can't figure out how some of these match up. For example, `core` (-c) is easy
```ruby
set_limit '*' do
  type 'soft'
  item 'core'
  value 'unlimited'
end
```

What 'item' would `max memory size` and `virtual memory` correspond to?

**Comment by jrwesolo** [comment]
I used http://linux.die.net/man/5/limits.conf as a template for what can be configured. Upon searching, it looks like `virtual memory` seems to map to `as` (http://shortrecipes.blogspot.de/2009/04/limitsconf-virtual-memory-limit.html). I am not sure what `max memory size` maps to. It may need to be set using a different mechanism.
